[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = h2zero/NimBLE-Arduino@^2.2.3

build_flags =
    -DCONFIG_BT_NIMBLE_LOG_LEVEL=5
    -DCONFIG_NIMBLE_CPP_LOG_LEVEL=4
